# REST API Application generated by DevHive AI
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from models import ItemModel
from service import CoreService
from pathlib import Path

app = FastAPI(title="Generated Service", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"]
)

service = CoreService()

@app.get("/")
def health_check():
    index_file = Path("static/index.html")
    if index_file.exists():
        return FileResponse(index_file)
    return {"status": "online", "engine": "DevHive Python Core"}

@app.get("/api/items")
def list_items():
    return service.get_all()

@app.post("/api/items")
def add_item(item: ItemModel):
    return service.create(item)
