# Data Models generated by DevHive AI
from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class ItemModel(BaseModel):
    id: Optional[int] = None
    title: str = Field(..., example="Örnek Kayıt")
    description: Optional[str] = None
    is_active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)
